version: '3.4'

services:
  server:
    image: server
    build:
      context: server
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - "db"
    volumes:
      - ./server:/app
  client:
    image: client
    build:
      context: client
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
  db:
    image: postgres:alpine
    env_file: 
      - ./.env 
    volumes:
      - ./pgdata:/var/lib/postgresql/data
volumes:
  datapg: