version: '3.4'

services:
  server:
    image: server
    build:
      context: server
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - "db"
    volumes:
      - ./server:/app
      - migrations:/app/instagram/migrations
      - media:/app/media/
  client:
    image: client
    build:
      context: client
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    user: "1000:1000"
  db:
    image: postgres:alpine
    env_file: 
      - ./.env 
    volumes:
      - datapg:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  datapg:
  migrations:
  media:

