# Generated by Django 3.2.4 on 2021-06-03 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('way', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='PostedImage',
        ),
    ]
